# Generated by Django 5.2.16 on 2026-08-04 03:44

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('inflates', models.BooleanField(default=True, help_text="Grow by the planner's inflation rate every 12 months from the projection start.")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'income extras',
                'ordering': ['payout_month', 'label'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('policy_type', models.CharField(blank=True, help_text='Term/Life, Health, Motor, ...', max_length=60)),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('premium_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Month the premium is debited. Quarterly and half-yearly policies repeat every 3 or 6 months from here.')),
                ('start_month', models.DateField(blank=True, help_text='Blank means the policy is already running.', null=True)),
                ('end_month', models.DateField(blank=True, help_text='Blank means ongoing. For a term policy enter the term in years and this is filled in for you.', null=True)),
                ('term_years', models.PositiveIntegerField(blank=True, help_text='Term policies: enter the term and the end month is computed from the start month.', null=True, verbose_name='Term (years)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'insurance policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, help_text='Equity MF, Direct Equity, Debt Fund, PPF, ...', max_length=60)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monthly_sip', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Monthly SIP')),
                ('sip_start_month', models.DateField(blank=True, help_text='Blank means the SIP is already running at the projection start.', null=True)),
                ('sip_end_month', models.DateField(blank=True, help_text='Blank means the SIP continues indefinitely.', null=True)),
                ('annual_stepup_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="The SIP grows by this much every 12 months from THIS fund's own SIP start month.", max_digits=6, verbose_name='Annual SIP step-up %')),
                ('expected_return_pct', models.DecimalField(blank=True, decimal_places=2, help_text="Blank falls back to the planner's default return.", max_digits=6, null=True, verbose_name='Expected return % p.a.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_month', models.DateField(help_text='Month the loan began. May be in the past relative to the projection start.')),
                ('principal_outstanding_today', models.DecimalField(blank=True, decimal_places=2, help_text="Outstanding as of the planner's start month, not at loan origination. Leave blank to back-solve it from the EMI, rate and tenure.", max_digits=14, null=True, verbose_name='Principal outstanding at projection start')),
                ('annual_interest_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Interest % p.a.')),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monthly EMI')),
                ('tenure_months', models.PositiveIntegerField(blank=True, help_text='Leave blank to derive from principal, rate and EMI.', null=True)),
                ('end_month_override', models.DateField(blank=True, help_text='Optional. If set, this wins over tenure and every derived end date.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField(default=datetime.date.today, help_text='Month zero of the projection. Stored as the 1st of the month.')),
                ('project_to_year', models.PositiveIntegerField(default=2040, help_text='Project through December of this year.')),
                ('expense_inflation_pct', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=6, verbose_name='Expense inflation % p.a.')),
                ('default_salary_hike_pct', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Applied in the hike month of any year with no explicit salary change.', max_digits=6, verbose_name='Default salary hike % p.a.')),
                ('default_hike_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, verbose_name='Default hike month')),
                ('bank_balance_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('bank_interest_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Credited monthly at one twelfth of this rate.', max_digits=6, verbose_name='Bank interest % p.a.')),
                ('default_investment_return_pct', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Used for any holding that does not set its own expected return.', max_digits=6, verbose_name='Default investment return % p.a.')),
                ('ef_target_months', models.PositiveIntegerField(default=6, help_text='Months of essential spending: living expenses + insurance + EMIs.', verbose_name='Emergency fund target (months)')),
                ('ef_target_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. If set, this overrides the months-based target.', max_digits=14, null=True, verbose_name='Emergency fund fixed target')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'planner settings',
                'verbose_name_plural': 'planner settings',
            },
        ),
        migrations.CreateModel(
            name='SalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(help_text='Salary changes from this month onward.')),
                ('monthly_in_hand', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, help_text='Promotion, switched company, ...', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_month'],
            },
        ),
    ]
