# Generated by Django 5.2.16 on 2026-08-04 04:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EPF', max_length=120)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The corpus as of the projection start month.', max_digits=14, verbose_name='Balance today')),
                ('employee_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Already deducted from your in-hand salary, so it is not charged again.', max_digits=14, verbose_name='Employee contribution / month')),
                ('employer_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Never passes through your bank account; it only grows the corpus.', max_digits=14, verbose_name='Employer contribution / month')),
                ('annual_return_pct', models.DecimalField(decimal_places=2, default=Decimal('8.25'), help_text='The EPF rate, credited monthly at one twelfth.', max_digits=6, verbose_name='Interest % p.a.')),
                ('start_month', models.DateField(blank=True, help_text='Blank means contributions are already running at the projection start.', null=True)),
                ('end_month', models.DateField(blank=True, help_text='Blank means contributions continue. Set this to the month you expect to stop contributing; the corpus keeps compounding either way.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
