# Generated by Django 5.2.16 on 2026-08-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_retirementaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentholding',
            name='return_3y_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The 3-year annualised (CAGR) figure from the fund's page.", max_digits=6, null=True, verbose_name='3Y return % p.a.'),
        ),
        migrations.AddField(
            model_name='investmentholding',
            name='return_5y_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The 5-year annualised (CAGR) figure from the fund's page.", max_digits=6, null=True, verbose_name='5Y return % p.a.'),
        ),
        migrations.AddField(
            model_name='investmentholding',
            name='return_basis',
            field=models.CharField(choices=[('custom', 'My own estimate'), ('3y', '3-year trailing return'), ('5y', '5-year trailing return')], default='custom', help_text='Which of the three figures below actually drives the projection.', max_length=10, verbose_name='Project using'),
        ),
        migrations.AlterField(
            model_name='investmentholding',
            name='expected_return_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Blank falls back to the planner's default return.", max_digits=6, null=True, verbose_name='Own estimate % p.a.'),
        ),
    ]
