# Generated by Django 5.2.16 on 2026-08-04 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_investmentholding_return_3y_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannersettings',
            name='surplus_pool_return_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), help_text="What the swept surplus earns while it sits unallocated -- roughly a liquid or arbitrage fund. Kept separate from your funds' returns.", max_digits=6, verbose_name='Surplus pool return % p.a.'),
        ),
        migrations.AddField(
            model_name='plannersettings',
            name='surplus_pool_today',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Un-earmarked savings you already hold that are neither your bank buffer nor a fund. Leave at zero if you have none.', max_digits=14, verbose_name='Surplus pool today'),
        ),
    ]
