# Generated by Django 5.2.16 on 2026-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_plannersettings_surplus_pool_return_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementaccount',
            name='monthly_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional ceiling on employee + employer together. EPF on the statutory wage ceiling is 12% of Rs 15,000 each side, so 3600 in total. Leave blank for no cap. Contributions track your salary until they hit this.', max_digits=14, null=True, verbose_name='Monthly contribution cap'),
        ),
    ]
