# Generated by Django 5.2.16 on 2026-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_expense_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannersettings',
            name='surplus_pool_return_pct',
        ),
        migrations.RemoveField(
            model_name='plannersettings',
            name='surplus_pool_today',
        ),
        migrations.AddField(
            model_name='incomeextra',
            name='payout_end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text="Optional. Leave blank for a single lump-sum payout. If set, the annual amount is split evenly across every month from 'Starts in' through here.", null=True, verbose_name='Ends in'),
        ),
        migrations.AlterField(
            model_name='incomeextra',
            name='payout_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, verbose_name='Starts in'),
        ),
        migrations.AlterField(
            model_name='plannersettings',
            name='ef_target_months',
            field=models.PositiveIntegerField(default=6, help_text='Months of essential spending: living expenses + insurance + EMIs. Purely a milestone shown against your bank balance -- nothing is moved because of it.', verbose_name='Emergency fund target (months)'),
        ),
    ]
