# Generated by Django 5.2.16 on 2026-09-26 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_pool_removal_and_bonus_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The full amount of this one-off purchase.', max_digits=14)),
                ('month', models.DateField(help_text='The month this was, or will be, spent.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'one-time expense',
                'verbose_name_plural': 'one-time expenses',
                'ordering': ['-month', 'name'],
            },
        ),
    ]
