# Generated by Django 5.2.16 on 2026-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_onetime_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeextra',
            name='end_month',
            field=models.DateField(blank=True, help_text='Blank means it continues indefinitely -- the same amount, every year, forever. Set this if the bonus is a fixed-term or one-off arrangement.', null=True, verbose_name='Ends in'),
        ),
        migrations.AddField(
            model_name='incomeextra',
            name='start_month',
            field=models.DateField(blank=True, help_text='Blank means this bonus is already running at the projection start.', null=True, verbose_name='Starts in'),
        ),
        migrations.AlterField(
            model_name='incomeextra',
            name='payout_end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text="Optional. Leave blank for a single lump-sum payout. If set, the annual amount is split evenly across every month from 'Paid in' through here.", null=True, verbose_name='Split through'),
        ),
        migrations.AlterField(
            model_name='incomeextra',
            name='payout_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, help_text="The month this pays out in, every year it's active.", verbose_name='Paid in'),
        ),
    ]
