# Generated by Django 5.2.16 on 2026-10-04 06:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_bonus_date_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text="What you need to have, in today's money terms as you expect to pay it.", max_digits=14)),
                ('target_month', models.DateField(help_text='The month the money is needed by.')),
                ('note', models.CharField(blank=True, max_length=160)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActualBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month these balances are as at the end of.')),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investment_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Investments')),
                ('pf_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Blank uses the projected figure.', max_digits=14, null=True, verbose_name='PF corpus')),
                ('loans_outstanding', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Blank uses the projected figure.', max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actual balance',
                'verbose_name_plural': 'actual balances',
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='one_actual_per_month')],
            },
        ),
    ]
